Fix unintelligible esprima error report (note the stacktrace which does not tell us anything useful, like where in the jison code did this originate)
```
node ./dist/cli-cjs-es5.js -o ./output/example-lex/ examples/lex.l -o examples/output/ -x

W:\Projects\sites\library.visyond.gov\80\lib\tooling\jison\node_modules\recast\node_modules\esprima\dist\esprima.js:5035
                throw this.createError(index, line, col, description);
                ^
Error: Line 2405: Invalid regular expression
    at ErrorHandler.constructError (W:\Projects\sites\library.visyond.gov\80\lib\tooling\jison\node_modules\recast\node_modules\esprima\dist\esprima.js:5012:22)
    at ErrorHandler.createError (W:\Projects\sites\library.visyond.gov\80\lib\tooling\jison\node_modules\recast\node_modules\esprima\dist\esprima.js:5028:27)
    at ErrorHandler.throwError (W:\Projects\sites\library.visyond.gov\80\lib\tooling\jison\node_modules\recast\node_modules\esprima\dist\esprima.js:5035:21)
    at Scanner.throwUnexpectedToken (W:\Projects\sites\library.visyond.gov\80\lib\tooling\jison\node_modules\recast\node_modules\esprima\dist\esprima.js:5164:35
)
    at Scanner.testRegExp (W:\Projects\sites\library.visyond.gov\80\lib\tooling\jison\node_modules\recast\node_modules\esprima\dist\esprima.js:6108:19)
    at Scanner.scanRegExp (W:\Projects\sites\library.visyond.gov\80\lib\tooling\jison\node_modules\recast\node_modules\esprima\dist\esprima.js:6206:27)
    at JSXParser.Parser.nextRegexToken (W:\Projects\sites\library.visyond.gov\80\lib\tooling\jison\node_modules\recast\node_modules\esprima\dist\esprima.js:2094
:35)
    at JSXParser.Parser.parsePrimaryExpression (W:\Projects\sites\library.visyond.gov\80\lib\tooling\jison\node_modules\recast\node_modules\esprima\dist\esprima
.js:2361:39)
    at JSXParser.parsePrimaryExpression (W:\Projects\sites\library.visyond.gov\80\lib\tooling\jison\node_modules\recast\node_modules\esprima\dist\esprima.js:466
:97)
    at JSXParser.Parser.inheritCoverGrammar (W:\Projects\sites\library.visyond.gov\80\lib\tooling\jison\node_modules\recast\node_modules\esprima\dist\esprima.js
:2285:37) {
  index: 94368,
  lineNumber: 2405,
  description: 'Invalid regular expression'
}
make[1]: *** [Makefile:75: example-lex] Error 1
```