BREAKING CHANGE: prevent cyclic references from occurring in yy & parseError hash structures: - get rid of the `destroy()` helper method - discard `lexer` and `parser` attributes in `hash`: these can be obtained via either appropriate `this` use or (new) provided APIs. - parser kernel tweaks:   + very tiny speed improvement by using Object.assign() for shallow copying where usable   + renamed `recovering` internal variable to the more readable `recoveringSymbolShiftCounter`, not being confusing any more (as there's also `recovered`)   + make `yydebug()` function available via shared `yy` when `parser.yy.yydebug` was enabled when invoking the parser.   + `parseError(msg, hash, exClass)` userland code can now edit the `hash` info object and have those changes end up in the error stack: we changed the kernel behaviour to *first* invoke `parseError()` *before* shallow-copying the error info hash for storage in the error stack and value stack (when performing an error recovery)   + `parseError()` calls are now source-identifiable, i.e. the `hash` info includes flags identifying the source of the error:
            // flags to help userland code to easily recognize what sort of error they're getting fed this time:
            isParserError: true,                // identifies this as a *parser* error (contrasting with a *lexer* error, which would have `isLexerError: true`)

            isParseErrorDuringRecovery: false,
            isParseAmbiguityError: false,
            isInternalParserError: false,
            isParserExceptionError: false,
            yyErrorInvoked: false,             // `true` when error is caused by call to `yyerror()`

- removing another potential cyclic ref: `yyval` does no longer contain a reference to the sharedState_yy (`yy`)